export default {
  FeatureName: 'DX Card Collection',
  features: [
    {
      tcid: '1',
      name: '@card-collection-no-tags-configured',
      path: '/digitalexperience/drafts/automation/regression/dx-card-collection/card-collections/collection-tags1',
      tags: '@da-dx-card-collection @regression @circleCi @anonymous',
      data: {
        keyword: 'cardcollection',
        cardTitle1: 'Cardcollection Quiz Analyst card',
        cardTitle2: 'Cardcollection All Tags card',
        cardTitle3: 'Cardcollection Healthcare-Video card',
        cardTitle4: 'Cardcollection Plans and pricing card',
        cardTitle5: 'Cardcollection Story-Services-IT card',
        cardTitle6: 'Cardcollection Retail-Decision-maker card',
        numberOfFilteredCards: 6,
      },
    },
    {
      tcid: '2',
      name: '@card-collection-one-tag-configured',
      path: '/digitalexperience/drafts/automation/regression/dx-card-collection/card-collections/collection-tags2',
      tags: '@da-dx-card-collection @regression @circleCi @anonymous',
      data: {
        cardTitle1: 'Cardcollection All Tags card',
        cardTitle2: 'Cardcollection Retail-Decision-maker card',
      },
    },
    {
      tcid: '3',
      name: '@card-collection-and-logic',
      path: '/digitalexperience/drafts/automation/regression/dx-card-collection/card-collections/collection-tags3',
      tags: '@da-dx-card-collection @regression @circleCi @anonymous',
      data: {
        cardTitle1: 'Cardcollection All Tags card',
        cardTitle2: 'Cardcollection Story-Services-IT card',
        oldestSort: 'oldest',
        newstSort: 'newest',
      },
    },
    {
      tcid: '4',
      name: '@card-collection-or-logic',
      path: '/digitalexperience/drafts/automation/regression/dx-card-collection/card-collections/collection-tags4',
      tags: '@da-dx-card-collection @regression @circleCi @anonymous',
      data: {
        cardTitle1: 'Cardcollection All Tags card',
        cardTitle2: 'Cardcollection Healthcare-Video card',
      },
    },
    {
      tcid: '5',
      name: '@card-collection-and-or-logic',
      path: '/digitalexperience/drafts/automation/regression/dx-card-collection/card-collections/collection-tags5',
      tags: '@da-dx-card-collection @regression @circleCi @anonymous',
      data: {
        cardTitle1: 'Cardcollection Quiz Analyst card',
        cardTitle2: 'Cardcollection All Tags card',
        cardTitle3: 'Cardcollection Healthcare-Video card',
      },
    },
    {
      tcid: '6',
      name: '@card-collection-card-collection-page-without-cards',
      path: '/digitalexperience/drafts/automation/regression/dx-card-collection/card-collections/collection-tags6',
      tags: '@da-dx-card-collection @regression @circleCi @anonymous',
    },
    {
      tcid: '7',
      name: '@multiple-card-collections-on-one-page',
      path: '/digitalexperience/drafts/automation/regression/dx-card-collection/card-collections/multiple-collections-on-page',
      tags: '@da-dx-card-collection @regression @circleCi @anonymous',
      data: {
        cardTitle1: 'Cardforfiltertest 1',
        cardTitle2: 'Cardforfiltertest 2',
        oldestSort: 'oldest',
        newstSort: 'newest',
        checkBoxAfterEffects: 'After Effects',
        btnRole: 'checkbox',
      },
    },
    {
      tcid: '8',
      name: '@card-collection-mutually-exclusive-filters-across-groups',
      path: '/digitalexperience/drafts/automation/regression/dx-card-collection/card-collections/collection-filters1',
      tags: '@da-dx-card-collection @regression @circleCi @anonymous',
      data: {
        keyword: 'Cardforfiltertest',
        numberOfFilteredCards: 11,
        topicFilterResults: 1,
        b2bFilterResults: 2,
        checkBoxAfterEffects: 'After Effects',
        btnRoleAfterEffects: 'checkbox',
        topicFilter: 'Topic',
        buttonRole: 'button',
        checkBoxFileSign: 'Fill & Sign',
        btnRoleFileSign: 'checkbox',
        checkBoxB2B: 'B2B',
        btnRoleB2B: 'checkbox',
      },
    },
    {
      tcid: '9',
      name: '@card-collection-or-logic-inside-same-group',
      path: '/digitalexperience/drafts/automation/regression/dx-card-collection/card-collections/collection-filters1',
      tags: '@da-dx-card-collection @regression @circleCi @anonymous',
      data: {
        keyword: 'Cardforfiltertest',
        numberOfFilteredCards: 1,
        topicPremiereResults: 2,
        afterEffectsResults: 3,
        checkBoxAfterEffects: 'After Effects',
        buttonRole: 'checkbox',
      },
    },
    {
      tcid: '10',
      name: '@card-collection-removing-one-of-several-active-filters',
      path: '/digitalexperience/drafts/automation/regression/dx-card-collection/card-collections/collection-filters1',
      tags: '@da-dx-card-collection @regression @circleCi @anonymous',
      data: {
        numberOfFilteredCards: 5,
        topicWorkFromAnywhere: 2,
        topicFilter: 'Topic',
        buttonRole: 'button',
        checkBoxXdFilter: 'XD',
        btnRoleXd: 'checkbox',
        workFromAnywhereFilter: 'Work from anywhere',
        btnRoleWorkFromAnywhere: 'checkbox',
      },
    },
    {
      tcid: '11',
      name: '@card-collection-duplicate-tag-handling',
      path: '/digitalexperience/drafts/automation/regression/dx-card-collection/card-collections/collection-filters1',
      tags: '@da-dx-card-collection @regression @circleCi @anonymous',
      data: {
        numberOfFilteredCards: 1,
        partnerConfidential: 1,
        invoices: 1,
        topicFilter: 'Topic',
        buttonRole: 'button',
        checkboxBridgeFilter: 'Bridge',
        btnRoleBridge: 'checkbox',
        checkboxAudienceFilter: 'Audience',
        btnRoleAudience: 'button',
        checkBoxPClFilter: 'Partner Confidential',
        btnRolePC: 'checkbox',
        checkBoxInvoicesFilter: 'Invoices',
        btnRoleInvoices: 'checkbox',
      },
    },
    {
      tcid: '12',
      name: '@card-collection-overlapping-filters-inside-one-group',
      path: '/digitalexperience/drafts/automation/regression/dx-card-collection/card-collections/collection-filters1',
      tags: '@da-dx-card-collection @regression @circleCi @anonymous',
      data: {
        numberOfFilteredCards: 5,
        audienceEnterpriseResult: 5,
        individualResults: 2,
        topicFilter: 'Topic',
        buttonRole: 'button',
        checkBox3DFilter: '3D design',
        btnRole3D: 'checkbox',
        checkboxAudienceFilter: 'Audience',
        btnRoleAudience: 'button',
        checkBoxEnterpriseFilter: 'Enterprise',
        btnRoleEnterprise: 'checkbox',
        checkBoxIndividualFilter: 'Individual',
        btnRoleIndividual: 'checkbox',
      },
    },
    {
      tcid: '13',
      name: '@card-collection-data-filter-test-case',
      path: '/digitalexperience/drafts/automation/regression/dx-card-collection/card-collections/collection-date',
      tags: '@da-dx-card-collection @regression @circleCi @anonymous',
      data: {
        keyword: 'Datefiltertestcard',
        numberOfSearcheddCards: 3,
        btnRoleProductCategories: 'button',
        productCategoriesFilter: 'Product Categories',
        dateFilter: 'Date',
        btnRoleDate: 'button',
        checkBoxCurrentMonth: 'Current Month',
        btnRoleCurrentMonth: 'button',
        numberOfCardsCurrentMonth: 1,
        checkBoxPreviousMonth: 'Previous Month',
        btnRolePreviousMonth: 'button',
        numberOfCardsPreviousMonth: 1,
        checkBoxLast90Days: 'Last 90 days',
        btnRoleLast90Days: 'button',
        numberOfCardsLast90Days: 3,
        checkBoxUIUX: 'UI and UX',
        btnRoleUIUX: 'checkbox',
        checkBoxAcrobatPDF: 'Acrobat and PDF',
        btnRoleAcrobatPDF: 'checkbox',
        checkBox3DAR: '3D and AR',
        btnRole3DAR: 'checkbox',
        checkBox3D: '3D',
        btnRole3D: 'checkbox',
      },
    },
  ],
};
